import { Injectable } from '@angular/core';
import { saveAs } from 'file-saver';

@Injectable({ providedIn: 'root' })
export class ImageService {
  private blobCache = new Map<string, Blob>();

  cacheBlob(url: string, blob: Blob) {
    this.blobCache.set(url, blob);
  }

  getCachedBlob(url: string): Blob | undefined {
    return this.blobCache.get(url);
  }

  async downloadImage(imageUrl: string, filename: string = 'aman-ai-image.png') {
    console.log('[ImageService] Downloading image:', imageUrl.substring(0, 50) + '...');
    
    // Attempt to download using fetch/blob for direct download
    try {
      const response = await fetch(imageUrl, { mode: 'cors' });
      const blob = await response.blob();
      saveAs(blob, filename);
      return; // Success
    } catch (error) {
      console.warn('[ImageService] Direct blob download failed (likely CORS), falling back to anchor link:', error);
    }

    // Fallback: Use anchor element to trigger download
    try {
      const link = document.createElement('a');
      link.href = imageUrl;
      link.download = filename;
      // Do not set target="_blank" to avoid opening a new tab if possible,
      // though some browsers require it for cross-origin.
      document.body.appendChild(link);
      link.click();
      document.body.removeChild(link);
    } catch (fallbackError) {
      console.error('[ImageService] Fallback download failed:', fallbackError);
      // Last resort: open in new tab
      window.open(imageUrl, '_blank');
    }
  }

  async downloadImageWithWatermark(imageUrl: string, filename: string = 'aman-ai-image.png') {
    try {
      // Use images.weserv.nl as a proxy to bypass CORS
      // We encode the original URL to pass it as a parameter
      const proxyUrl = `https://images.weserv.nl/?url=${encodeURIComponent(imageUrl)}`;
      
      const response = await fetch(proxyUrl);
      const blob = await response.blob();
      
      // Since we are using an external proxy, we can't easily add a custom watermark
      // locally on the canvas without CORS issues if we don't control the proxy.
      // However, this proxy is very fast and handles the CORS issue, 
      // allowing for a direct download.
      
      saveAs(blob, filename);
    } catch (error) {
      console.error('[ImageService] Proxy download failed, falling back to direct link:', error);
      this.downloadImage(imageUrl, filename); // Fallback
    }
  }

  async shareImage(imageUrl: string, title: string = 'Aman AI Image') {
    if (!navigator.share) {
      this.downloadImage(imageUrl);
      return;
    }
    
    try {
      // Use the same proxy to fetch the image as a blob
      const proxyUrl = `https://images.weserv.nl/?url=${encodeURIComponent(imageUrl)}`;
      const response = await fetch(proxyUrl);
      const blob = await response.blob();
      
      // Create a File object from the blob
      const file = new File([blob], 'image.png', { type: 'image/png' });
      
      // Share the file
      await navigator.share({ 
        files: [file], 
        title: title,
        text: 'Check out this image generated by Aman AI!'
      });
    } catch (error) {
      console.error('[ImageService] Failed to share image as file, falling back to link:', error);
      // Fallback to sharing the link
      try {
        await navigator.share({ title: title, url: imageUrl });
      } catch (fallbackError) {
        console.error('[ImageService] Fallback share failed:', fallbackError);
        this.downloadImage(imageUrl);
      }
    }
  }

  private dataUrlToBlob(dataUrl: string): Blob {
    const parts = dataUrl.split(',');
    const mime = parts[0].match(/:(.*?);/)?.[1] || 'image/png';
    const bstr = atob(parts[1]);
    let n = bstr.length;
    const u8arr = new Uint8Array(n);
    while (n--) {
      u8arr[n] = bstr.charCodeAt(n);
    }
    return new Blob([u8arr], { type: mime });
  }
}
